index.html

The previous link 403'ed.
N.b. The home page of [coveralls.io](https://coveralls.io) links to https://coveralls.io/r/lodash/lodash, which in turn redirects to the added link (https://coveralls.io/github/lodash/lodash). Figured it was a bit faster (avoiding the redirect) and perhaps the /r/ link may change again, so I've used the second URL.

Update coveralls.io URL in index.html

---

assets/css/main.scss

This gives larger screen estate to the actual documentation. The menu for mobile shouldn’t be affected.
| Initial behaviour | New behaviour |
|---|---|
| ![Initial](https://cloud.githubusercontent.com/assets/813865/16543910/9cb8e650-4122-11e6-8558-5e6ed7b4d9a0.gif) | ![New](https://cloud.githubusercontent.com/assets/813865/16543913/a75cc5c2-4122-11e6-9d1f-5505ac2ba157.gif) |

Make lodash navbar smaller on docs page.

---

_layouts/docs.html
assets/js/docs.js

If the version of the page isn't in the version selector, add it and make it selected so the dropdown displays the right version. This will be important when there are more versions added, but not in the dropdown. E.g., when 4.14.0 is released, 4.13.1 will be removed from the dropdown but still available.
Also, add a link to legacy lodash 1.3.1 version that links to github since that page wasn't able to be ported.

Fixes to version select

---

assets/css/_docs.scss

I removed the `#` link but I let you be the judge of that. I really think it belongs in front of the title (kind of like [bootstrap's docs](http://getbootstrap.com/css/ does it, but they show it on hover).
Is it possible to have classes to avoid these kind of funky selectors? (`html.docs .doc-container > div > div h3 + p a`)

style docs' `source` and `npm package` links

---

assets/css/_docs.scss
assets/css/_media-queries.scss

Hey.
The documentation is a bit sluggish and stuttery when it comes to scroll...
I identified the issue, which is constant repaints on scroll and addressed it by promoting both TOC (`.toc-container`) and the content section (`.doc-container`) onto their own GPU layers.
Now the browsers are able to do the compositing cheaply on GPU, rather than repaint all the content all over again on scroll.
Let me know if that looks good and if you need anything else (more info?) from me. ;)
Thanks,
Daniel.

Fix Docs' scroll performance issues

---

assets/css/_default.scss

Making it more explicit rather than relying on the shortcut fixes issue on Safari.

Fix header not wrapping issue on Safari/iOS.

---

assets/css/_docs.scss
assets/css/_media-queries.scss

This eliminates the horizontal scroll, and slightly increases the font-size. Note that I've drastically increased the width of the sidebar, but this (IMO) plays well across all screen sizes.
To be merged along with #43. With it, the sidebar will be more readable.
WCAG AA color contrasts in another PR.

Tweak docs sidebar width & font size

---

assets/js/docs.js

This is a common shortcut across many tools, including both Underscore and
Ramda's docs, so it should be intuitive to most devs.
I've confirmed that this does not interfere with typing `/` in the REPL.

Focus on the search input by typing `/`

---

assets/js/docs.js

So I found that the logic to update the visibility and state of the content wasn't being called when someone clicked on a search item and reset the `searchValue`.
To fix this I abstracted the meat of the update process into a separate method and call that from the `onChangeSearch`.

Update visibility when search value clicked

---

assets/css/_custom-builds.scss
assets/css/_default.scss
assets/css/_docs.scss
assets/css/_home.scss
assets/css/_media-queries.scss

See #57, I've converted the root (html) font-size to 62.5%, and divided any em/rem by 0.625. This makes rem scaling on a much easier to read, base 10: 24px = 2.4rem.

Standardize font-size and em/rem units into rem

---

assets/css/_docs.scss
assets/css/_mixins.scss
assets/css/main.scss

I let you decide if you want to apply `minimal-scrollbar()` to `.doc-container` as well. I did not because the scrollbar ends up being very tiny (and I'm on 1440p, so I can't even imagine 1080p).

style the toc-container scrollbar on webkit

---

assets/css/_media-queries.scss

This does 2 things:
1. Give the same whitespace before and after the gray border between the logo and the title, in the header.
2. Gives enough room for the menu to fit on an iPhone 5/SE.

improve irregular logo spacing on mobile

---

assets/css/_media-queries.scss

On small phones like the iPhone 5/SE, there was too much horizontal padding, making lines a bit short for reading.
<table>
<tr>
<th>
Before
</th>
<th>
After
</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

remove some padding on doc container on mobile

---

assets/css/_docs.scss

This plays a little weird on a very small screen on desktop. The scrollbar is very very wide (beyond the viewport). It seems to be because of the margin and padding set to -999 and 999rem. What was @zackhall intention with this?
```
h3 {
...
margin: 0 -999rem;
padding: 3.2rem 999rem;
...
}
```
https://github.com/lodash/lodash.com/blob/master/assets/css/_docs.scss#L74-L75

make it possible to vertically scroll through long method names

---

assets/css/_docs.scss
assets/js/docs.js

**Before:**
**After:** 
**Before**
**After**
**Before**
**After**

Leverage flexbox to improve search items alignments

---

assets/css/_default.scss

Before with Courier New
After with default monospace:
I don't have Consolas installed on my Ubuntu 16.04. So the code looks extremely bad with Courier New font-family. The default monospace looks better.

Remove Courier New from font-family

---

assets/js/docs.js

While migrating a project from lodash v3 to v4, I wanted to confirm that method signatures hadn't changed. I had to search for the method each time I switched between versions.
I thought it would be helpful to jump to the current chosen method while switching between versions, instead of having to find the method each time.

Add location.hash to version change

---

assets/css/_carbon.scss
assets/js/docs.js

I'm seeing the add scroll with the content instead of staying fixed.
The problem occurs on:
* chrome: 54.0.2840.99 m
* Window 10 x64
* With and without adblock
* In incognito mode and without (no extensions are loaded in incognito)
It doesn't occur on:
* Firefox
* Edge (though it jitters while scrolling. This should also be fixed with this PR)
I propose we move it outside the toc scrollable to make sure it stays fixed.

The ad in the toc in the docs doesn't stay position fixed

---

assets/css/_default.scss

Header in Safari 9 seems to be squished to 0 height without setting flex-shrink to 0

Set flex-shrink on header to 0. fixes #126

---

assets/js/docs.js

The React script faded the first two characters of a method no matter what. Added a regex match to verify the menu item's actually beginning with `_.`

Only fade methods actually beginning with _.

---

_headers

This doesn't implicitly whitelist http when the page is served via https, as explained by Scott Helme in
https://scotthelme.co.uk/optimising-twitters-csp-header/
See also https://www.w3.org/TR/CSP2/#match-source-expression, specifically:
> 4.5. If the source expression does **not** have a scheme, return _does not match_ if any of the following are true:
>   1. the scheme of the protected resource’s URL is a case insensitive match for HTTP, and url-scheme is **not** a case insensitive match for either HTTP or HTTPS
>   2. the scheme of the protected resource’s URL is not a case insensitive match for HTTP, and url-scheme is **not** a case insensitive match for the scheme of the protected resource’s URL.

CSP: Omit https:// from source expressions

---

assets/css/_docs.scss
assets/js/docs.js

I just found this ~issue~ enhancement (#165) was still open.
The code just adds a css class to every doc title when rendering it and adds the `expanderClick` on `onClick` event.

Added collapsible-behaviour to docs title

---

docs/4.17.10.html

As seen on [the website](https://lodash.com/docs/4.17.10#VERSION), links for `_.VERSION` and `_.templateSettings` are not being displayed unless hovered over.
This PR removes additional anchor tags around both headings so they display like other source headings.

Fix source link headings not displaying

---

docs/4.17.11.html

this made the function name hidden by default and visible only on hover, like the anchor icon

fix: remove unnecessary wrap on  function name

---

assets/css/_docs.scss

Noticed that ya'll were getting a weird border radius happening on Safari mobile, so I thought I'd fix it for ya. Thanks for the project!

Removes input border radius on Safari mobile

---

index.html
per-method-packages.html

https://github.com/lodash/lodash/issues/4427
Here is the page for quick reference:
```
---
id: per-method-packages
title: Lodash per method packages
layout: default
---
<section>
<h1>Per Method Packages</h1>
<p>
Lodash methods are available in standalone <a href="https://www.npmjs.com/browse/keyword/lodash-modularized">per method packages</a>
like <code>lodash.mapvalues</code>, <code>lodash.pickby</code>, etc.
These packages contain only the code the method depends on.
</p>
<p>
<strong>
However, use of these packages is discouraged and they <a href="https://github.com/lodash/lodash/issues/3838#issuecomment-398592530">will be removed in v5</a>.
</strong>
</p>
<p>
Although they may seem more lightweight, they will usually increase the size of
<code>node_modules</code> and webpack/rollup …
```

feat: add /per-method-packages page

---

assets/js/docs.js

We'll be shipping a major update to embeds that significantly improves performance, but unfortunately it will result in the layout being off on the lodash page due to its direct manipulation of RunKit's iframe. The good news is that the new version will behave the way it's currently changed to behave on lodash.com by default. This change just puts an if guard around the code in order to have the transition be smooth, after wee go live next week it can bee removed or other changes can be made too (there will be some new features you might be interested in). For now though, this should be a no-op currently and properly prepare the page for the update. Please do let me know if you have any questions or concerns.

Guard iframe manipulation on RunKit embed to prepare for new version.

---

_headers

In an effort to not cross-contaminate embed with cookies from our main site, we will be hosting embeds on their own domain. This commit prepares the CSP to allow for this when we switch over.

Add *.runkit-embed.com to content security policy in preparation for RunKit embed iframes living on this new domain.

---

_headers

Unfortunately I didn't realize that while child-src normally applies to iframes, it does not when frame-src is *also* present. This adds it there too.
Apologies for the separate commits.

frame-src overrides child-src if present.

---

assets/css/_home.scss

https://github.com/lodash/lodash.com/issues/269
There is a distortion in the social media division due to uneven widths and I have corrected the widths
Before
After

corrected widths for social media division

---

assets/css/_home.scss

.btn-twitter-follow {
width: 120px;
}
is changed to
.btn-twitter-follow {
width: 16rem;
}
and update (follow @bestie js) twitter button width issue and its compatible with all media width ,and use rem property that will work on all media width then pixel value to hardcore ,Thank You

corrected width for social media app for all media width using rem property

---

assets/css/_docs.scss

Related  issues #210 #212 
The input action in docs search box result in page reflow and then block js, ultimately leading to search lagging.
I'm not sure what directly caused it, but uncertain height of  `.doc-container` element maybe one significant indirect cause (I have already exclude factors such as React re-rendering, event handling, and search function consumption). 
I speculate `.doc-main` style `flex: 1 1 auto` causing this uncertain behavior. Changing it to `flex:1 1 100% | flex:1 1 100vh | flex:1 1 0 `  indeed effective for me. Additionally, Set the `.doc-container` element height to a fixed value also works.
The performance after modification:
ps: I always browsing lodash.com website in desktop as a PWA application, so I used to think the issue was due to PWA performance.😂

pref: improve the search performance
